In [41]:
import numpy as np
from sklearn import datasets

data_iris=datasets.load_iris().data

In [42]:
notre_tableau = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(notre_tableau)
type(notre_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


numpy.ndarray

In [43]:
mon_array_bidimensionnel=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mon_array_bidimensionnel)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
print(mon_array_bidimensionnel[0,2])

print(mon_array_bidimensionnel[0,2])

print(mon_array_bidimensionnel[:,0])

print(mon_array_bidimensionnel[0,:])

3
3
[1 4 7]
[1 2 3]


In [45]:
mon_array_bidimensionnel[0,0]="texte"

ValueError: invalid literal for int() with base 10: 'texte'

In [46]:
mon_array_bidimensionnel.dtype

dtype('int32')

In [47]:
mon_array_bidimensionnel = np.array([[1.5,2,3],[4,5.2,6],[7,8,9.1]], dtype = float)
print(mon_array_bidimensionnel)
mon_array_bidimensionnel.dtype

[[1.5 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.  9.1]]


dtype('float64')

In [48]:
mon_array_zeros = np.zeros((4,6))
print(mon_array_zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [49]:
mon_array_ones = np.ones((4,6))
print(mon_array_ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [50]:
mon_array_random=np.random.random((4,2))
print(mon_array_random)

[[0.22405549 0.94700736]
 [0.22240837 0.88082833]
 [0.28332861 0.97621432]
 [0.60412771 0.37429988]]


In [51]:

print(data_iris)
print(data_iris.dtype)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [52]:
np.savetxt("iris_2.csv",data_iris, delimiter=";")

In [53]:
print(data_iris[2,1])
print(data_iris[0,0])
print(data_iris[0,1])
print(data_iris[0,2])

3.2
5.1
3.5
1.4


In [54]:
data_iris[2,1]=4
print(data_iris[2,1])

4.0


In [55]:
data_iris[2,1]=3.2
print(data_iris[2,1])

3.2


In [56]:
data_iris[data_iris>2]

array([5.1, 3.5, 4.9, 3. , 4.7, 3.2, 4.6, 3.1, 5. , 3.6, 5.4, 3.9, 4.6,
       3.4, 5. , 3.4, 4.4, 2.9, 4.9, 3.1, 5.4, 3.7, 4.8, 3.4, 4.8, 3. ,
       4.3, 3. , 5.8, 4. , 5.7, 4.4, 5.4, 3.9, 5.1, 3.5, 5.7, 3.8, 5.1,
       3.8, 5.4, 3.4, 5.1, 3.7, 4.6, 3.6, 5.1, 3.3, 4.8, 3.4, 5. , 3. ,
       5. , 3.4, 5.2, 3.5, 5.2, 3.4, 4.7, 3.2, 4.8, 3.1, 5.4, 3.4, 5.2,
       4.1, 5.5, 4.2, 4.9, 3.1, 5. , 3.2, 5.5, 3.5, 4.9, 3.6, 4.4, 3. ,
       5.1, 3.4, 5. , 3.5, 4.5, 2.3, 4.4, 3.2, 5. , 3.5, 5.1, 3.8, 4.8,
       3. , 5.1, 3.8, 4.6, 3.2, 5.3, 3.7, 5. , 3.3, 7. , 3.2, 4.7, 6.4,
       3.2, 4.5, 6.9, 3.1, 4.9, 5.5, 2.3, 4. , 6.5, 2.8, 4.6, 5.7, 2.8,
       4.5, 6.3, 3.3, 4.7, 4.9, 2.4, 3.3, 6.6, 2.9, 4.6, 5.2, 2.7, 3.9,
       5. , 3.5, 5.9, 3. , 4.2, 6. , 2.2, 4. , 6.1, 2.9, 4.7, 5.6, 2.9,
       3.6, 6.7, 3.1, 4.4, 5.6, 3. , 4.5, 5.8, 2.7, 4.1, 6.2, 2.2, 4.5,
       5.6, 2.5, 3.9, 5.9, 3.2, 4.8, 6.1, 2.8, 4. , 6.3, 2.5, 4.9, 6.1,
       2.8, 4.7, 6.4, 2.9, 4.3, 6.6, 3. , 4.4, 6.8, 2.8, 4.8, 6.

In [57]:
data_iris[data_iris>2].shape

(422,)

In [58]:
data_iris[data_iris>2].shape[0]

422

In [59]:
data_iris > 2

array([[ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True, False, False],
 

In [60]:
data_iris[data_iris[:,1]>3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3

In [61]:
notre_tableau= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print("Conetenu de notre_tableau :")
print(notre_tableau)
print("Nouveau tableau après fancy indexing :")
indice = np.array([[4,10,5],[12,8,9]])
A = notre_tableau[indice]
print(A)
print(A[0,2])

Conetenu de notre_tableau :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nouveau tableau après fancy indexing :
[[ 5 11  6]
 [13  9 10]]
6


In [62]:
notre_tableau[:3]

array([1, 2, 3])

In [63]:
notre_tableau[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [64]:
notre_tableau[3:7]

array([4, 5, 6, 7])

In [65]:
notre_tableau[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [66]:
notre_tableau[3:8:3]

array([4, 7])

In [67]:
notre_tableau[2::2]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [68]:
data_iris[:2,:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [69]:
data_iris[145:,2:]

array([[5.2, 2.3],
       [5. , 1.9],
       [5.2, 2. ],
       [5.4, 2.3],
       [5.1, 1.8]])

In [70]:
data_iris[0,:]

array([5.1, 3.5, 1.4, 0.2])

In [71]:
data_iris[:,0]

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [72]:
data_iris[-1,:]

array([5.9, 3. , 5.1, 1.8])

In [73]:
sous_tableau = notre_tableau[:5]
sous_tableau

array([1, 2, 3, 4, 5])

In [74]:
sous_tableau[0] = 10
sous_tableau

array([10,  2,  3,  4,  5])

In [75]:
notre_tableau

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
notre_tableau= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

sous_tableau = notre_tableau[:5].copy()
sous_tableau[0] = 10
print(sous_tableau)
print(notre_tableau)

[10  2  3  4  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [77]:
mon_tableau = np.array([[10,11,12],[13,14,15],[16,17,18]])
mon_tableau

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [78]:
np.add(mon_tableau,10)

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [79]:
A = np.multiply(mon_tableau,20)
print(A)
print(mon_tableau)

[[200 220 240]
 [260 280 300]
 [320 340 360]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [80]:
mon_tableau_2 = np.array([10,20,30])
print(mon_tableau_2)
print(mon_tableau)

[10 20 30]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [81]:
np.subtract(mon_tableau,mon_tableau_2)

array([[  0,  -9, -18],
       [  3,  -6, -15],
       [  6,  -3, -12]])

In [82]:
mon_tableau_2

array([10, 20, 30])

In [83]:
mon_tableau_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mon_tableau_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
np.multiply(mon_tableau,mon_tableau_3)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [85]:
print("Somme sur l'ensemble des éléments :")
print(np.sum(data_iris, axis=0))
print("somme par ligne: ")
print(np.sum(data_iris, axis=1))

Somme sur l'ensemble des éléments :
[876.5 458.6 563.7 179.9]
somme par ligne: 
[10.2  9.5  9.4  9.4 10.2 11.4  9.7 10.1  8.9  9.6 10.8 10.   9.3  8.5
 11.2 12.  11.  10.3 11.5 10.7 10.7 10.7  9.4 10.6 10.3  9.8 10.4 10.4
 10.2  9.7  9.7 10.7 10.9 11.3  9.7  9.6 10.5 10.   8.9 10.2 10.1  8.4
  9.1 10.7 11.2  9.5 10.7  9.4 10.7  9.9 16.3 15.6 16.4 13.1 15.4 14.3
 15.9 11.6 15.4 13.2 11.5 14.6 13.2 15.1 13.4 15.6 14.6 13.6 14.4 13.1
 15.7 14.2 15.2 14.8 14.9 15.4 15.8 16.4 14.9 12.8 12.8 12.6 13.6 15.4
 14.4 15.5 16.  14.3 14.  13.3 13.7 15.1 13.6 11.6 13.8 14.1 14.1 14.7
 11.7 13.9 18.1 15.5 18.1 16.6 17.5 19.3 13.6 18.3 16.8 19.4 16.8 16.3
 17.4 15.2 16.1 17.2 16.8 20.4 19.5 14.7 18.1 15.3 19.2 15.7 17.8 18.2
 15.6 15.8 16.9 17.6 18.2 20.1 17.  15.7 15.7 19.1 17.7 16.8 15.6 17.5
 17.8 17.4 15.5 18.2 18.2 17.2 15.7 16.7 17.3 15.8]


In [86]:
print(np.mean(data_iris, axis=0))
print(np.std(data_iris, axis=0))

[5.84333333 3.05733333 3.758      1.19933333]
[0.82530129 0.43441097 1.75940407 0.75969263]


In [87]:
print(np.max(data_iris, axis=0))

[7.9 4.4 6.9 2.5]


In [88]:
print(np.max(data_iris,axis=1))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [89]:
colonne_1 = data_iris[data_iris[:,4]==1]
colonne_2 = data_iris[data_iris[:,4]==2]
colonne_3 = data_iris[data_iris[:,4]==3]

print(np.mean(colonne_1,axis=0))
print(np.mean(colonne_2,axis=0))
print(np.mean(colonne_3,axis=0))

IndexError: index 4 is out of bounds for axis 1 with size 4

In [90]:
print("Attribut size")
print(data_iris.size)
print("Attribut shape")
print(data_iris.shape)
print("Attribut dtype")
print(data_iris.dtype)
print("Attribut ndim")
print(data_iris.ndim)

Attribut size
600
Attribut shape
(150, 4)
Attribut dtype
float64
Attribut ndim
2


In [91]:
data_iris.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [92]:
print(data_iris[(data_iris[:,4] == 3) & (data_iris[:, 3] > 2)])

IndexError: index 4 is out of bounds for axis 1 with size 4

In [93]:
np.append(notre_tableau,[21,22,23,24,25])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [94]:
np.append(data_iris,[[10,10,10,10,10]],axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [95]:
np.insert(notre_tableau,1,42)

array([ 1, 42,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [96]:
np.insert(notre_tableau, 1, [42,43,44,45,46])

array([ 1, 42, 43, 44, 45, 46,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20])

In [97]:
np.insert(data_iris, 1, [10,10,10,10,10], axis = 0)

ValueError: could not broadcast input array from shape (1,5) into shape (1,4)

In [98]:
np.delete(data_iris, 1, axis = 1)

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.2],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.4, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [99]:
np.delete(data_iris, [1,2,3,4], axis=0)

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3

In [100]:
np.delete(notre_tableau,1)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [101]:
notre_tableau

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [102]:
notre_tableau_1, notre_tableau_2, notre_tableau_3,notre_tableau_4 = np.split(notre_tableau, [2,6,18])
print(notre_tableau_1, notre_tableau_2, notre_tableau_3,notre_tableau_4)

[1 2] [3 4 5 6] [ 7  8  9 10 11 12 13 14 15 16 17 18] [19 20]


In [103]:
array=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("avant division")
print(array)
array1, array2 = np.vsplit(array, [2])
print("Après division")
print("array1: ",array1)
print("array2: ",array2)

avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
array1:  [[ 2.  5.  6.]
 [ 9. 10. 11.]]
array2:  [[5. 6. 9.]]


In [104]:
array=np.array([[2,5,6],[9,10,11],[5,6,9]], dtype="float")
print("avant division")
print(array)
array1, array2 = np.hsplit(array, [2])
print("Après division")
print("array1: ",array1)
print("array2: ",array2)

avant division
[[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]
Après division
array1:  [[ 2.  5.]
 [ 9. 10.]
 [ 5.  6.]]
array2:  [[ 6.]
 [11.]
 [ 9.]]


In [105]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9])
array3 = np.array([6,7,8,9])
print(array1)
print(array2)
np.concatenate([array1,array2,array3])

[1 2 3 4 5]
[6 7 8 9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9, 6, 7, 8, 9])

In [106]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = "float")
array2 = np.array([[2,5,6],[9,10,11],[5,6,9]], dtype = "float")
print("array1 :",array1)
print("array2 :",array2)
np.concatenate([array1,array2])

array1 : [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
array2 : [[ 2.  5.  6.]
 [ 9. 10. 11.]
 [ 5.  6.  9.]]


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.]])

In [107]:
array3 = np.array([[4,10,13],[7,14,15]],dtype="float")
np.concatenate([array1,array2,array3])

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 2.,  5.,  6.],
       [ 9., 10., 11.],
       [ 5.,  6.,  9.],
       [ 4., 10., 13.],
       [ 7., 14., 15.]])

In [108]:
array1 = np.array([15,16,47])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="float")
print(array1)
print(5*"-")
print(array2)
print(5*"-")
print(np.vstack([array1,array2]))
array1 = np.array([[15],[16],[47]])
print(5*"-")

[15 16 47]
-----
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
-----
[[15. 16. 47.]
 [ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
-----


In [109]:
print(array1)
print(5*"-")
print(array2)
print(5*"-")
print(np.hstack([array1,array2]))

[[15]
 [16]
 [47]]
-----
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
-----
[[15.  1.  2.  3.]
 [16.  4.  5.  6.]
 [47.  7.  8.  9.]]


In [110]:
## multiplication de deux tableaux ndarrays
array2*array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [111]:
# produit matriciel entre les deux matrices array2
np.mat(array2)*np.mat(array2)

matrix([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [116]:
data_iris2 = np.delete(data_iris,3,axis = 1)
moyenne = np.mean(data_iris2, axis=1)

data_iris3 = np.insert(data_iris, 4 , moyenne, axis = 1)
print(data_iris3)

[[5.1        3.5        1.4        0.2        3.33333333]
 [4.9        3.         1.4        0.2        3.1       ]
 [4.7        3.2        1.3        0.2        3.06666667]
 [4.6        3.1        1.5        0.2        3.06666667]
 [5.         3.6        1.4        0.2        3.33333333]
 [5.4        3.9        1.7        0.4        3.66666667]
 [4.6        3.4        1.4        0.3        3.13333333]
 [5.         3.4        1.5        0.2        3.3       ]
 [4.4        2.9        1.4        0.2        2.9       ]
 [4.9        3.1        1.5        0.1        3.16666667]
 [5.4        3.7        1.5        0.2        3.53333333]
 [4.8        3.4        1.6        0.2        3.26666667]
 [4.8        3.         1.4        0.1        3.06666667]
 [4.3        3.         1.1        0.1        2.8       ]
 [5.8        4.         1.2        0.2        3.66666667]
 [5.7        4.4        1.5        0.4        3.86666667]
 [5.4        3.9        1.3        0.4        3.53333333]
 [5.1        3

In [117]:
iris_mean = np.mean(data_iris[:,:4], axis=1)
iris_mean
print(np.insert(data_iris, 4,iris_mean, axis=1))

[[5.1   3.5   1.4   0.2   2.55 ]
 [4.9   3.    1.4   0.2   2.375]
 [4.7   3.2   1.3   0.2   2.35 ]
 [4.6   3.1   1.5   0.2   2.35 ]
 [5.    3.6   1.4   0.2   2.55 ]
 [5.4   3.9   1.7   0.4   2.85 ]
 [4.6   3.4   1.4   0.3   2.425]
 [5.    3.4   1.5   0.2   2.525]
 [4.4   2.9   1.4   0.2   2.225]
 [4.9   3.1   1.5   0.1   2.4  ]
 [5.4   3.7   1.5   0.2   2.7  ]
 [4.8   3.4   1.6   0.2   2.5  ]
 [4.8   3.    1.4   0.1   2.325]
 [4.3   3.    1.1   0.1   2.125]
 [5.8   4.    1.2   0.2   2.8  ]
 [5.7   4.4   1.5   0.4   3.   ]
 [5.4   3.9   1.3   0.4   2.75 ]
 [5.1   3.5   1.4   0.3   2.575]
 [5.7   3.8   1.7   0.3   2.875]
 [5.1   3.8   1.5   0.3   2.675]
 [5.4   3.4   1.7   0.2   2.675]
 [5.1   3.7   1.5   0.4   2.675]
 [4.6   3.6   1.    0.2   2.35 ]
 [5.1   3.3   1.7   0.5   2.65 ]
 [4.8   3.4   1.9   0.2   2.575]
 [5.    3.    1.6   0.2   2.45 ]
 [5.    3.4   1.6   0.4   2.6  ]
 [5.2   3.5   1.5   0.2   2.6  ]
 [5.2   3.4   1.4   0.2   2.55 ]
 [4.7   3.2   1.6   0.2   2.425]
 [4.8   3.

In [118]:
iris_column_mean = np.mean(data_iris, axis = 0)
print(np.insert(data_iris,data_iris.shape[0], iris_column_mean, axis=0))

[[5.1        3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [4.7        3.2        1.3        0.2       ]
 [4.6        3.1        1.5        0.2       ]
 [5.         3.6        1.4        0.2       ]
 [5.4        3.9        1.7        0.4       ]
 [4.6        3.4        1.4        0.3       ]
 [5.         3.4        1.5        0.2       ]
 [4.4        2.9        1.4        0.2       ]
 [4.9        3.1        1.5        0.1       ]
 [5.4        3.7        1.5        0.2       ]
 [4.8        3.4        1.6        0.2       ]
 [4.8        3.         1.4        0.1       ]
 [4.3        3.         1.1        0.1       ]
 [5.8        4.         1.2        0.2       ]
 [5.7        4.4        1.5        0.4       ]
 [5.4        3.9        1.3        0.4       ]
 [5.1        3.5        1.4        0.3       ]
 [5.7        3.8        1.7        0.3       ]
 [5.1        3.8        1.5        0.3       ]
 [5.4        3.4        1.7        0.2       ]
 [5.1        